#define MAINPREFIX x
#define PREFIX soil

#define MAJOR 0
#define MINOR 0
#define PATCHLVL 0
#define BUILD 0

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 1.66

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(Soil - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(Soil - COMPONENT)
#endif
